FROM public.ecr.aws/lambda/python:3.9

RUN yum install -y make && \
    yum clean all

ADD requirements-lambda.txt .

RUN pip install --no-cache-dir -r requirements-lambda.txt && \
    python -m spacy download fr_core_news_lg && \
    rm -rf /root/.cache

ENV TF_CPP_MIN_LOG_LEVEL "2"
ENV NLTK_DATA /tmp

ADD . ${LAMBDA_TASK_ROOT}

CMD ["lambda.lambda_handler"]
